[dependencies]
base = "0.11.1"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.1"

[package]
name = "ovs-fixed"
version = "0.1.0"
description = "An OVS scheme for a fixed cycles donation"
repository = "https://github.com/icdevsorg/ovs-fixed.mo"
keywords = ["open value sharing","cycles"]
